SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;
-- articles DDL
CREATE TABLE `articles` (`id` INT NOT NULL AUTO_INCREMENT,
`title` VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "文章标题",
`type` TINYINT NOT NULL Comment "文章类型",
`content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "正文",
`brief` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "摘要",
`status` TINYINT NOT NULL Comment "状态",
`sort` INT NULL Comment "排序",
`show_start_time` DATETIME NULL Comment "展示开始时间",
`show_end_time` DATETIME NULL Comment "展示结束时间",
`is_top` TINYINT NOT NULL Comment "是否置顶",
`creator` VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
`deleted_at` DATETIME NULL,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 2 ROW_FORMAT = Dynamic COMMENT = "文章表";
-- blog_attaches DDL
CREATE TABLE `blog_attaches` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`blog_id` BIGINT NULL DEFAULT 0 Comment "博客id",
`attach` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`poster` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "视频封面",
`sort` INT NULL DEFAULT 0 Comment "排序",
`type` TINYINT NULL DEFAULT 0 Comment "类型 0 图片 1 视频 3食物 4食谱 5就餐记录",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
INDEX `idx_blog_id`(`blog_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 2 ROW_FORMAT = Dynamic COMMENT = "博客附件";
-- blog_comments DDL
CREATE TABLE `blog_comments` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`blog_id` BIGINT NULL DEFAULT 0 Comment "博客id",
`user_id` BIGINT NULL DEFAULT 0 Comment "用户id",
`content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`parent_id` BIGINT NULL DEFAULT 0 Comment "父评论id",
`like` INT NULL DEFAULT 0 Comment "点赞数量",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
INDEX `idx_blog_id`(`blog_id` ASC) USING BTREE,
INDEX `idx_parent_id`(`parent_id` ASC) USING BTREE,
INDEX `idx_user_id`(`user_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "博客评论";
-- blog_locations DDL
CREATE TABLE `blog_locations` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`blog_id` BIGINT NOT NULL,
`latitude` DECIMAL(10,6) NOT NULL,
`longitude` DECIMAL(10,6) NOT NULL,
`name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
`address` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 2 ROW_FORMAT = Dynamic COMMENT = "博客位置表";
-- blog_topics DDL
CREATE TABLE `blog_topics` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`blog_id` BIGINT NOT NULL,
`topic_id` BIGINT NOT NULL,
UNIQUE INDEX `idx_blog_topic`(`blog_id` ASC,`topic_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "博客话题表";
-- blogs DDL
CREATE TABLE `blogs` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`user_id` BIGINT NULL DEFAULT 0 Comment "用户id",
`title` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' Comment "标题",
`likes` INT UNSIGNED NULL DEFAULT 0 Comment "点赞数量",
`views` INT UNSIGNED NULL DEFAULT 0 Comment "查看数量",
`comments` INT UNSIGNED NULL DEFAULT 0 Comment "评论数量",
`favs` INT UNSIGNED NULL DEFAULT 0 Comment "收藏数量",
`content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`visibility` TINYINT(1) NULL DEFAULT 1 Comment "状态 0隐藏 1所有人可见 2仅自己可见 3仅好友可见",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
`deleted_at` DATETIME NULL,
INDEX `idx_user_id`(`user_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 2 ROW_FORMAT = Dynamic COMMENT = "博客";
-- cats DDL
CREATE TABLE `cats` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "分类名称",
`pid` BIGINT NULL DEFAULT 0 Comment "上级分类",
`sort` INT NULL Comment "排序",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "编辑时间",
`deleted_at` DATETIME NULL,
UNIQUE INDEX `name`(`name` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 890 ROW_FORMAT = Dynamic COMMENT = "食品分类";
-- checkin_records DDL
CREATE TABLE `checkin_records` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`user_id` BIGINT NOT NULL,
`target_calorie` INT NOT NULL Comment "当日目标卡路里",
`total_calorie` INT NOT NULL Comment "当日摄入总卡路里",
`result` ENUM("success","fail_over","fail_under") CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "打卡结果",
`date` DATE NOT NULL Comment "打卡日期，一个用户一天一条记录",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
UNIQUE INDEX `idx_user_id_date`(`user_id` ASC,`date` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "打卡记录";
-- favorites DDL
CREATE TABLE `favorites` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`user_id` BIGINT NULL DEFAULT 0 Comment "用户id",
`target` BIGINT NULL DEFAULT 0 Comment "食物id",
`type` TINYINT NULL DEFAULT 0 Comment "类型 1 帖子 2 食物 3食谱",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
INDEX `target_type`(`target` ASC,`type` ASC) USING BTREE,
UNIQUE INDEX `user_target_type`(`user_id` ASC,`target` ASC,`type` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic;
-- follows DDL
CREATE TABLE `follows` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`user_id` BIGINT NULL DEFAULT 0 Comment "用户id",
`follow_id` BIGINT NULL DEFAULT 0 Comment "关注id",
`is_attention` TINYINT(1) NULL DEFAULT 0 Comment "是否互相关注 0否 1是",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
UNIQUE INDEX `idx_user_follow_id`(`user_id` ASC,`follow_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic;
-- food_make_steps DDL
CREATE TABLE `food_make_steps` (`id` INT NOT NULL AUTO_INCREMENT,
`step_no` INT NULL,
`name` INT NULL,
`food` INT NULL Comment "食物id",
`ingredient` INT NULL Comment "食材id",
`number` DECIMAL(10,2) NULL Comment "所需多少单位的食材",
`unit` INT NULL Comment "单位",
`remark` INT NULL,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic;
-- food_nutrients DDL
CREATE TABLE `food_nutrients` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`food_id` BIGINT NOT NULL Comment "所属食物ID",
`water` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "水分(g/100g)",
`kcal` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "热量(kcal/100g)",
`pro` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "蛋白质(g/100g)",
`fat` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "脂肪(g/100g)",
`carb` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "碳水化合物(g/100g)",
`sugar` DOUBLE(10,2) NULL DEFAULT 0.00 Comment "糖分(g/100g)",
`fiber` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "膳食纤维(g/100g)",
`chol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "胆固醇(mg/100g)",
`purine` DOUBLE(10,2) NULL DEFAULT 0.00 Comment "总嘌呤(mg/100g)",
`gi` DOUBLE(10,2) NULL DEFAULT 0.00 Comment "血糖指数",
`vit_a` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "维生素A(μg/100g)",
`vit_c` DOUBLE(10,2) NULL DEFAULT 0.00 Comment "维生素C(mg/100g)",
`vit_d` DOUBLE(10,2) NULL DEFAULT 0.00 Comment "维生素D(μg/100g)",
`vit_e` DOUBLE(10,2) NULL DEFAULT 0.00 Comment "维生素E(mg/100g)",
`folic` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "叶酸(mg/100g)",
`na` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "钠(mg/100g) - Sodium",
`cal` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "钙(mg/100g) - Calcium",
`iron` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "铁(mg/100g) - Iron",
`kal` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "钾(mg/100g) - Potassium",
`mag` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "镁(mg/100g) - Magnesium",
`zinc` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "锌(mg/100g) - Zinc",
`sel` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "硒(μg/100g) - Selenium",
`cup` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "铜(mg/100g) - Cuprum",
`mang` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "锰(mg/100g) - Manganese",
`iod` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "碘(μg/100g) - Iodine",
`fa` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "总脂肪酸(g/100g)",
`sfa` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "饱和脂肪酸(g/100g)",
`mufa` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "单不饱和脂肪酸(g/100g)",
`pufa` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "多不饱和脂肪酸(g/100g)",
`origin` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "产地/备注",
INDEX `idx_food_id`(`food_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 2591 ROW_FORMAT = Dynamic COMMENT = "食物营养成分缩写表";
-- food_tags DDL
CREATE TABLE `food_tags` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`food_id` INT UNSIGNED NOT NULL Comment "食物ID",
`tag_id` INT UNSIGNED NOT NULL Comment "标签ID",
UNIQUE INDEX `uk_food_tag`(`food_id` ASC,`tag_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 13562 ROW_FORMAT = Dynamic COMMENT = "食物标签关联表";
-- food_units DDL
CREATE TABLE `food_units` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT Comment "主键ID",
`food_id` INT UNSIGNED NOT NULL Comment "食物ID",
`unit_id` INT UNSIGNED NOT NULL Comment "单位ID",
`weight` DECIMAL(10,2) NOT NULL Comment "换算重量 (1单位 ≈ ? g)",
`is_default` TINYINT(1) NOT NULL DEFAULT 0 Comment "是否为默认单位",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注 (如: 杯(约250ml))",
`thumb` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "示意图",
INDEX `fk_foodunit_unit`(`unit_id` ASC) USING BTREE,
UNIQUE INDEX `uk_food_unit`(`food_id` ASC,`unit_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 3084 ROW_FORMAT = Dynamic COMMENT = "食物单位换算关系表";
-- foods DDL
CREATE TABLE `foods` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT Comment "食物ID",
`name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "食物名称",
`cat_id` INT UNSIGNED NULL Comment "食物分类",
`user_id` INT UNSIGNED NULL Comment "所属用户",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态",
`is_ingredient` TINYINT NULL Comment "是否食材 1是 2不是",
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "更新时间",
`deleted_at` TIMESTAMP NULL,
`is_common` TINYINT NULL DEFAULT 2 Comment "是否常见食物 1是 2不是",
`coze_status` INT NULL DEFAULT 0 Comment "0未处理 1已处理",
INDEX `idx_cat_id`(`cat_id` ASC) USING BTREE,
INDEX `idx_name`(`name` ASC,`status` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 2630 ROW_FORMAT = Dynamic COMMENT = "食物基础信息与营养表";
-- likes DDL
CREATE TABLE `likes` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`user_id` INT NOT NULL Comment "用户ID",
`target` INT NOT NULL Comment "目标ID (动态ID/食谱ID/用户ID等)",
`type` TINYINT(1) NOT NULL DEFAULT 1 Comment "类型: 1=动态, 2=食谱, 3=用户",
`created_at` DATETIME NULL Comment "点赞时间",
`updated_at` DATETIME NULL,
INDEX `target_type`(`target` ASC,`type` ASC) USING BTREE,
UNIQUE INDEX `user_target_type`(`user_id` ASC,`target` ASC,`type` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "通用点赞记录表";
-- meal_record_foods DDL
CREATE TABLE `meal_record_foods` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`meal_id` BIGINT NULL DEFAULT 0 Comment "就餐记录id",
`user_id` BIGINT NULL,
`food_id` BIGINT NULL DEFAULT 0 Comment "食物id",
`unit_id` BIGINT NULL DEFAULT 0 Comment "单位",
`nutrition` JSON NULL Comment "营养成分",
`number` DECIMAL(10,2) NULL DEFAULT 1.00 Comment "分量",
`image` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "图片",
`name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
INDEX `idx_crated_at`(`created_at` ASC) USING BTREE,
INDEX `idx_food_id`(`food_id` ASC) USING BTREE,
INDEX `idx_meal_id`(`meal_id` ASC) USING BTREE,
INDEX `idx_unit_id`(`unit_id` ASC) USING BTREE,
INDEX `idx_user_id`(`user_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 11 ROW_FORMAT = Dynamic COMMENT = "就餐记录食物";
-- meal_records DDL
CREATE TABLE `meal_records` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`user_id` BIGINT NULL DEFAULT 0 Comment "所属用户",
`type` TINYINT NULL DEFAULT 0 Comment "类型 0 早餐 1 午餐 2 晚餐 3加餐",
`nutrition` JSON NULL Comment "营养信息",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
`meal_date` DATE NOT NULL DEFAULT 'curdate()',
`latitude` DECIMAL(10,6) NULL Comment "纬度",
`longitude` DECIMAL(10,6) NULL Comment "经度",
`address` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
INDEX `idx_user_id_type`(`user_id` ASC,`type` ASC) USING BTREE,
UNIQUE INDEX `uk_user_type_date`(`user_id` ASC,`type` ASC,`meal_date` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 7 ROW_FORMAT = Dynamic COMMENT = "就餐记录";
-- menu_dishes DDL
CREATE TABLE `menu_dishes` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键id",
`dishes_id` BIGINT NOT NULL Comment "菜品id",
`base_dishes_id` BIGINT NULL Comment "菜品基础id",
`meal_type` INT NOT NULL DEFAULT 1 Comment "类型(1-菜品,2-套餐)",
`dishes_num` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "菜品编码",
`custom_id` INT NOT NULL Comment "自定义id",
`inventory_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "存货id(数据同步)",
`dishes_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "菜品名称",
`alias_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "菜品别称",
`pinyin_initials` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "菜品名称拼音首字母",
`pinyin_full` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "菜品名称全拼",
`bar_code` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "条形码",
`intro` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "菜品简介",
`cook_id` BIGINT NOT NULL DEFAULT -1 Comment "菜品灶类ID",
`type_id` BIGINT NOT NULL DEFAULT 1 Comment "菜品类型ID",
`classify_id` BIGINT NULL Comment "菜品分类id(自定义)",
`effect_id` BIGINT NULL Comment "菜品功效id（强筋健骨）",
`style_id` BIGINT NULL Comment "菜系id(鲁系主食，沪系主食)",
`if_local_feature` INT NULL Comment "是否本地特色(1是2否)",
`dishes_depart` INT NULL Comment "菜别(1小荤,2大荤,3素)",
`sequence` INT NULL DEFAULT -1 Comment "次序（1餐前,2餐后）",
`pungency_degree` INT NULL Comment "辣度",
`sales_mode` INT NOT NULL DEFAULT 1 Comment "销售方式(1按份,2称重)",
`size_type` INT NULL DEFAULT 1 Comment "规格类型(1-标准,2-大小份)",
`size_json` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "菜品规格",
`weight` DOUBLE(10,2) NOT NULL DEFAULT 100.00 Comment "每份重量(g)",
`large_weight` DOUBLE(10,2) NULL Comment "大份份量",
`little_weight` DOUBLE(10,2) NULL Comment "小份份量",
`weight_deviation` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "质量偏差(g)",
`price` INT NOT NULL DEFAULT 999999 Comment "菜品基础单价(分)",
`unit_price` INT NOT NULL DEFAULT 100 Comment "称重单位多少克(默认100g)",
`large_price` INT NULL Comment "大份单价",
`little_price` INT NULL Comment "小份单价",
`image_url` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "菜品图片url",
`particulars` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "菜品详情",
`recommend` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "菜品推荐",
`index_recommend` INT NOT NULL DEFAULT 2 Comment "首页推荐(1-推荐,2-不推荐)",
`like_survey` INT NOT NULL DEFAULT 2 Comment "点赞调查标识(1-是,2-否)",
`like_batch` BIGINT NULL Comment "点赞调查批次号",
`like_num` INT NOT NULL DEFAULT 0 Comment "点赞数",
`initial_score` INT NULL DEFAULT 80 Comment "菜品初始推荐值",
`calories` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "热量(千卡/份)",
`protein` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "蛋白质(g/份)",
`fat` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "脂肪(g/份)",
`carbohydrate` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "碳水化合物(g/份)",
`dietary_fiber` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "膳食纤维(g/份)",
`cholesterol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "胆固醇(mg/份)",
`calcium` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "钙(mg/份)",
`sodium` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "钠(mg/份)",
`purine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "总嘌呤含量(mg/100g)",
`iron` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "铁(mg/100g)",
`iodine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "碘(μg/100g)",
`kalium` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "钾(mg/100g)",
`vitamin_a` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "维生素a(μg/100g)",
`vitamin_c` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "维生素c(mg/100g)",
`vitamin_e` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "维生素e(g/100g)",
`magnesium` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "镁(mg/100g)",
`zinc` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "锌(mg/100g)",
`glycemic_index` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "血糖生成指数(GI)",
`sort` INT NOT NULL DEFAULT 0 Comment "优先级",
`canteen_id` BIGINT NOT NULL DEFAULT -1 Comment "食堂ID",
`shopstall_id` BIGINT NOT NULL DEFAULT -1 Comment "档口或店铺id",
`hide_flag` INT NOT NULL DEFAULT 2 Comment "隐藏标识(1隐藏,2展示)",
`convert_flag` INT NOT NULL DEFAULT 1 Comment "结果图转注册图",
`material_cost` INT NULL Comment "成本价",
`gross_profit` INT NULL Comment "毛利",
`gross_profit_rate` DOUBLE(10,2) NULL Comment "毛利率",
`public_dishes` INT NOT NULL DEFAULT 2 Comment "是否是公共菜品(1-是,2-否,)",
`area_id` BIGINT NOT NULL DEFAULT -1 Comment "区域id",
`del_flag` INT NOT NULL DEFAULT 2 Comment "删除标识(1删除,2正常)",
`revision` INT NOT NULL DEFAULT 0 Comment "乐观锁",
`crby` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "创建人",
`crtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`upby` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "更新人",
`uptime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "更新时间",
`praise_rate` DOUBLE(10,2) NULL Comment "好评率",
`monthly_sales` INT NULL Comment "月销",
`intelligent_recipe` INT NOT NULL DEFAULT 1 Comment "是否智能菜谱适用",
`main_cooking_method` INT NULL Comment "主要烹饪方式",
`treatment_dishes_flag` INT NULL DEFAULT 2 Comment "是否为治疗菜(1是,2否)",
`sub_alias_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "别名2",
INDEX `index_del_flag`(`del_flag` ASC) USING BTREE,
INDEX `index_dishes_id`(`dishes_id` ASC) USING BTREE,
INDEX `menu_dishes_area_id_IDX`(`area_id` ASC) USING BTREE,
INDEX `menu_dishes_base_dishes_id_IDX`(`base_dishes_id` ASC) USING BTREE,
INDEX `menu_dishes_canteen_id_IDX`(`canteen_id` ASC) USING BTREE,
INDEX `menu_dishes_custom_id_IDX`(`custom_id` ASC) USING BTREE,
INDEX `menu_dishes_hide_flag_IDX`(`hide_flag` ASC) USING BTREE,
INDEX `menu_dishes_shopstall_id_IDX`(`shopstall_id` ASC) USING BTREE,
INDEX `menu_dishes_size_json_IDX`(`size_json` ASC) USING BTREE,
INDEX `menu_dishes_type_id_IDX`(`type_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "菜品信息";
-- menu_dishes_make DDL
CREATE TABLE `menu_dishes_make` (`id` INT NOT NULL AUTO_INCREMENT,
`step_no` INT NULL Comment "步骤数",
`base_dishes_id` BIGINT NULL Comment "菜品基础id",
`make_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "步骤名称",
`make_time_start` INT NULL Comment "时长范围开始",
`make_time_end` INT NULL Comment "时长范围结束",
`make_center_temperature_start` INT NULL Comment "中心温度开始",
`make_center_temperature_end` INT NULL Comment "中心温度结束",
`make_oil_temperature_start` INT NULL Comment "油温开始",
`make_oil_temperature_end` INT NULL Comment "油温结束",
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic;
-- menu_material DDL
CREATE TABLE `menu_material` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键id",
`area_id` BIGINT NULL Comment "区域id",
`material_id` BIGINT NOT NULL Comment "食材id",
`material_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "食材名称",
`material_code` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "原料编码",
`pinyin_initials` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "拼音首字母",
`pinyin_full` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "拼音全拼",
`image_url` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "原料图片",
`nutrition_id` BIGINT NULL Comment "营养信息",
`category_id` BIGINT NULL Comment "类别id",
`material_type` INT NOT NULL DEFAULT 1 Comment "原料类型(1原料2商品)",
`bar_code` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "条码",
`unit_id` BIGINT NULL Comment "单位",
`sale_price` INT NULL Comment "销售价",
`unit_price` INT NULL Comment "进价",
`sales_mode` INT NULL DEFAULT 1 Comment "售卖类型(1计量2散称)",
`reserve_rate` INT NOT NULL DEFAULT 0 Comment "预留比例(0-100)",
`shelf_life_type` INT NULL Comment "保质期类型 1年 2月 3日",
`shelf_life_days` INT NULL Comment "保质期数",
`synopsis` VARCHAR(8000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "简介",
`del_flag` INT NOT NULL DEFAULT 2 Comment "删除标识(1删除,2正常)",
`revision` INT NOT NULL DEFAULT 0 Comment "乐观锁",
`crby` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "创建人",
`crtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`upby` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "更新人",
`uptime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "更新时间",
`pur_price_ceiling` INT NULL Comment "采购价格上限",
`cert_id` BIGINT NULL Comment "资格证书",
`big_category_id` BIGINT NULL Comment "大类id",
`size` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "规格",
`tax_rate` INT NULL Comment "税率",
`disable_status` INT NULL Comment "禁用状态1启用 2禁用",
`convert_grams` INT NULL Comment "转换数量  单位g",
`brand_id` BIGINT NULL Comment "品牌 id",
`dietary_category` INT NULL Comment "膳食宝塔类别",
`spu_id` BIGINT NULL Comment "商品spuId",
`attrs` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "销售属性值id{attr_value_id}-{attr_value_id} 多个销售属性值id逗号分隔",
`attr_values` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "销售属性值，多个销售属性值/拼接",
`gross_proportion` DECIMAL(10,2) NULL DEFAULT 100.00 Comment "毛净比(%)",
`if_use_batch_inventory` INT NULL DEFAULT 2 Comment "是否使用批次库存操作(1是2否)",
`cost_accounting_style` INT NULL Comment "成本核算方式(1先入先出,2移动加权平均法,3月度加权平均法)",
`gross_net_type` INT NOT NULL DEFAULT 1 Comment "毛净类型(1净料2毛料)",
`valuable_goods` INT NULL Comment "高价值货品品(1是2否)",
`process_price` INT NULL Comment "加工工序总价 分/公斤",
`unit_price_start_date` DATE NULL Comment "进价开始日期",
`unit_price_end_date` DATE NULL Comment "进价结束日期",
`alias_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "别名",
`sub_alias_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "别名2",
`third_party_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "三方ID",
INDEX `idx_area_status_id`(`area_id` ASC,`del_flag` ASC,`disable_status` ASC) USING BTREE,
INDEX `idx_material_name`(`material_name` ASC) USING BTREE,
INDEX `idx_unique_material_code`(`material_code` ASC) USING BTREE,
INDEX `index_area_id`(`area_id` ASC) USING BTREE,
INDEX `index_category_id`(`category_id` ASC) USING BTREE,
INDEX `index_material_type`(`material_type` ASC) USING BTREE,
INDEX `index_material_unit`(`material_id` ASC,`unit_id` ASC) USING BTREE,
INDEX `index_zh_id`(`material_id` ASC,`category_id` ASC,`unit_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "商家食材原料信息";
-- menu_material_category DDL
CREATE TABLE `menu_material_category` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键id",
`area_id` BIGINT NULL Comment "区域id",
`category_id` BIGINT NOT NULL Comment "类别id",
`category_num` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "类别编码",
`category_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "类别名称",
`parent_id` BIGINT NOT NULL DEFAULT -1 Comment "父类id",
`category_type` INT NOT NULL DEFAULT 1 Comment "类型(1原料2商品)",
`del_flag` INT NOT NULL DEFAULT 2 Comment "删除标识(1-删除,2-正常)",
`revision` INT NOT NULL DEFAULT 0 Comment "乐观锁",
`crby` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "创建人",
`crtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`upby` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "更新人",
`uptime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "更新时间",
`level` INT NULL Comment "等级(0,1,2,3)",
`big_category_id` BIGINT NULL Comment "大类id",
`disable_status` INT NULL DEFAULT 1 Comment "禁用状态1启用 2禁用",
INDEX `index_area_id`(`area_id` ASC) USING BTREE,
INDEX `index_category_id`(`category_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "原料类别表";
-- menu_material_dishes DDL
CREATE TABLE `menu_material_dishes` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键id",
`dishes_id` BIGINT NOT NULL Comment "菜品id",
`material_id` BIGINT NOT NULL Comment "食材id",
`weight` DOUBLE(10,2) NOT NULL Comment "食材重量(g)",
`material_type` INT NOT NULL Comment "材料类型(1主料,2辅料,3配料)",
`del_flag` INT NOT NULL DEFAULT 2 Comment "删除标识(1删除,2正常)",
`revision` INT NOT NULL DEFAULT 0 Comment "乐观锁",
`crby` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "创建人",
`crtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`upby` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "更新人",
`uptime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "更新时间",
`gross_net_ratio` DOUBLE(10,2) NULL Comment "毛净比",
`gross_weight` DOUBLE(10,2) NULL Comment "毛料重量",
`cost_price` INT NULL Comment "毛料成本价",
INDEX `index_dishes_id`(`dishes_id` ASC) USING BTREE,
INDEX `index_material_id`(`material_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "菜品食材关联";
-- menu_nutrition DDL
CREATE TABLE `menu_nutrition` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键id",
`nutrition_id` BIGINT NOT NULL Comment "食材营养id",
`nutrition_code` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0' Comment "食材编码",
`nutrition_name` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "食材名称",
`nutrition_image_url` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "食材图片url",
`weight` DOUBLE(10,2) NOT NULL DEFAULT 100.00 Comment "标准份重量(g)",
`price` INT NOT NULL DEFAULT 999999 Comment "食材基础单价(分)",
`color` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "食材颜色",
`category_id` BIGINT NULL Comment "类别id",
`big_type` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "食材大类",
`little_type` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "食材小类",
`label` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "标签(海产海鱼、淡水鱼、海鲜类等)",
`processing_method` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "加工方式",
`processing_time` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "加工时间(min)",
`recommended_combination` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "推荐组合(以英文逗号分割,食材编码区分不超过20个)",
`combination_not_recommended` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "不推荐组合(以英文逗号分割,以食材编码区分不超过20个)",
`edible` DOUBLE(10,2) NOT NULL DEFAULT 100.00 Comment "可食部分(g/100g)",
`water` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "水分(g/100g)",
`calories` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "热量(千卡/100g)",
`protein` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "蛋白质(g/100g)",
`fat` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "脂肪(g/100g)",
`carbohydrate` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "碳水化合物(g/100g)",
`dietary_fiber` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "不溶性膳食纤维(g/100g)",
`cholesterol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "胆固醇(mg/100g)",
`ash` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "灰分(g/100g)",
`vitamin_a` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "维生素a(μg/100g)",
`carotene` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "胡萝卜素(μg/100g)",
`thiamine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "硫胺素(mg/100g)",
`riboflavin` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "核黄素(mg/100g)",
`niacin` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "烟酸/尼克酸(mg/100g)",
`vitamin_c` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "维生素c(mg/100g)",
`vitamin_d` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "维生素d(μg/100g)",
`vitamin_e` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "维生素e(mg/100g)",
`del_flag` INT NOT NULL DEFAULT 2 Comment "删除标识(1删除,2正常)",
`choline` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "胆碱(mg/100g)",
`biotin` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "生物素/维生素7(ug/100g)",
`pantothenic_acid` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "泛酸(mg/100g)",
`guanine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "鸟嘌呤(mg/100g)",
`adenine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "腺嘌呤(mg/100g)",
`hypoxanthine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "次黄嘌呤(mg/100g)",
`xanthine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "黄嘌呤(mg/100g)",
`purine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "总嘌呤含量(mg/100g)",
`glycemic_index` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "血糖生成指数(GI)",
`total_phytosterol_content` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "植物甾醇总含量(mg/100g)",
`cereal_sterol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "β-谷甾醇(mg/100g)",
`camelia_sterol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "菜油甾醇(mg/100g)",
`sterol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "豆甾醇(mg/100g)",
`cereal_steranol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "β-谷甾烷醇(mg/100g)",
`rapesanol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "菜油甾烷醇(mg/100g)",
`rapeseed_steranol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "菜子甾醇(mg/100g)",
`lutein_zeaxanthin` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "叶黄素+玉米素(μg/100g)",
`quercetin` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "槲皮素(mg/100g)",
`myricetin` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "杨梅黄酮(mg/100g)",
`luteolin` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "玉米黄酮(mg/100g)",
`kaem_pferol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "坎二菲醇(mg/100g)",
`apigenin` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "芹菜配基(mg/100g)",
`isoflavone` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "大豆异黄酮总含量(mg/100g)",
`daidzein` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "黄豆苷元(mg/100g)",
`genistein` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "染料木黄酮(mg/100g)",
`glycitein` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "黄豆黄素(mg/100g)",
`anthocyan` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "花青素(mg/100g鲜重,包含飞燕草素、矢车菊素、芍药素)",
`resveratrol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "白藜芦醇(μg/100g)",
`polydatin` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "白藜芦醇苷(μg/100g)",
`origin_place` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "备注/原产地",
`calcium` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "钙(mg/100g)",
`phosphorus` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "磷(mg/100g)",
`kalium` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "钾(mg/100g)",
`sodium` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "钠(mg/100g)",
`magnesium` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "镁(mg/100g)",
`iron` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "铁(mg/100g)",
`zinc` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "锌(mg/100g)",
`selenium` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "硒(μg/100g)",
`cuprum` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "铜(mg/100g)",
`manganese` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "锰(mg/100g)",
`isoleucine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "异亮氨酸(mg/100g)",
`leucine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "亮氨酸(mg/100g)",
`lysine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "赖氨酸(mg/100g)",
`saa_total` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "含硫氨基酸(mg/100g)",
`aaa_total` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "芳香族氨基酸(mg/100g)",
`threonine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "苏氨酸(mg/100g)",
`tryptophan` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "色氨酸(mg/100g)",
`valine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "缬氨酸(mg/100g)",
`arginine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "精氨酸(mg/100g)",
`histidine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "组氨酸(mg/100g)",
`alanine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "丙氨酸(mg/100g)",
`aspartic_acid` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "天冬氨酸(mg/100g)",
`glutamate` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "谷氨酸(mg/100g)",
`glycine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "甘氨酸(mg/100g)",
`proline` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "脯氨酸(mg/100g)",
`serine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "丝氨酸(mg/100g)",
`fatty_acid` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "脂肪酸(g/100g可食部)",
`saturated_fatty_acid` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "饱和脂肪酸(g/100g可食部)",
`monounsaturated_fatty_acid` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "单不饱和脂肪酸(g/100g可食部)",
`polyunsaturated_fatty_acid` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "多不饱和脂肪酸(g/100g可食部)",
`iodine` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "碘(μg/100g)",
`folic` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "叶酸(mg/100g)",
`retinol` DOUBLE(10,2) NOT NULL DEFAULT 0.00 Comment "视黄醇(μg/100g)",
`default_flag` INT NOT NULL DEFAULT 2 Comment "是否默认(1-默认,2-非默认)",
`revision` INT NOT NULL DEFAULT 0 Comment "乐观锁",
`crby` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "创建人",
`crtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`upby` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' Comment "更新人",
`uptime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "更新时间",
INDEX `index_nutrition_id`(`nutrition_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "食材营养基础信息_新";
-- recipe_attaches DDL
CREATE TABLE `recipe_attaches` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`recipe_id` BIGINT NULL DEFAULT 0 Comment "食谱id",
`attach` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
INDEX `idx_recipe_id`(`recipe_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "食谱附件";
-- recipe_foods DDL
CREATE TABLE `recipe_foods` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`recipe_id` BIGINT NULL DEFAULT 0 Comment "食谱id",
`food_id` BIGINT NULL DEFAULT 0 Comment "食物id",
`number` DECIMAL(10,2) NULL DEFAULT 0.00 Comment "分量",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
INDEX `idx_food_id`(`food_id` ASC) USING BTREE,
INDEX `idx_recipe_id`(`recipe_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic;
-- recipes DDL
CREATE TABLE `recipes` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`user_id` BIGINT NULL DEFAULT 0 Comment "用户id",
`name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`summary` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`like` INT NULL DEFAULT 0 Comment "点赞数量",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
INDEX `idx_user_id`(`user_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "食谱";
-- tags DDL
CREATE TABLE `tags` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "标签名称 (如: 红烧, 健身)",
`type` TINYINT NOT NULL DEFAULT 1 Comment "一级分类: 1-餐次, 2-口味, 3-营养特点, 4-烹饪方式, 5-适用人群, 6-食材状态, 7-过敏原,8-品牌产地,9-时令季节,10-特殊场景,11-存储方式",
`meta_type` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "二级分类/维度 (用于前端筛选分组, 如: Cooking,人群, 状态)",
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`deleted_at` DATETIME NULL,
INDEX `idx_type_name`(`type` ASC,`name` ASC) USING BTREE,
UNIQUE INDEX `uk_name`(`name` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 2454 ROW_FORMAT = Dynamic COMMENT = "标签表";
-- tasks DDL
CREATE TABLE `tasks` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`task_id` BIGINT NOT NULL Comment "业务任务ID",
`user_id` BIGINT NOT NULL Comment "用户ID",
`type` TINYINT NOT NULL DEFAULT 1 Comment "任务类型 1食品识别",
`params` JSON NULL Comment "请求参数",
`additional` JSON NULL Comment "附加参数",
`response` JSON NULL,
`run_status` TINYINT NOT NULL DEFAULT 1 Comment "1进行中 2已结束",
`complete_status` TINYINT NOT NULL DEFAULT 1 Comment "1进行中 2成功 3失败",
`retry_count` TINYINT NOT NULL DEFAULT 0 Comment "重试次数",
`worker` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "处理机器/进程",
`error_msg` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
`completed_at` DATETIME NULL,
INDEX `idx_completed`(`completed_at` ASC) USING BTREE,
INDEX `idx_created`(`created_at` ASC) USING BTREE,
INDEX `idx_fetch`(`run_status` ASC,`complete_status` ASC,`created_at` ASC) USING BTREE,
INDEX `idx_user_task`(`user_id` ASC,`task_id` ASC) USING BTREE,
INDEX `idx_status`(`run_status` ASC,`complete_status` ASC) USING BTREE,
UNIQUE INDEX `uk_task_id`(`task_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 6 ROW_FORMAT = Dynamic;
-- topic_relation DDL
CREATE TABLE `topic_relation` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键ID",
`topic_id` BIGINT NOT NULL Comment "话题ID",
`target_id` BIGINT NOT NULL Comment "关联对象ID（博客ID、餐食记录ID等）",
`target_type` TINYINT NOT NULL Comment "关联类型 1博客 2餐食记录 3其他",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
INDEX `idx_target`(`target_id` ASC,`target_type` ASC) USING BTREE,
UNIQUE INDEX `idx_topic_target`(`topic_id` ASC,`target_type` ASC,`target_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "话题关联表";
-- topics DDL
CREATE TABLE `topics` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "话题ID",
`title` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "话题标题",
`thumb` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "话题封面图片",
`description` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "话题描述",
`status` TINYINT NULL DEFAULT 1 Comment "状态 1正常 0禁用",
`join` INT NULL DEFAULT 0 Comment "参与人数",
`post` INT NULL DEFAULT 0 Comment "关联文章/餐食记录数",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "更新时间",
`deleted_at` DATETIME NULL,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "话题表";
-- units DDL
CREATE TABLE `units` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT Comment "单位ID",
`name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "单位名称",
`type` ENUM("weight","count","volume","package","service","length") CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "单位类型 ",
`desc` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "描述",
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "更新时间",
`delete_at` TIMESTAMP NULL,
`deleted_at` DATETIME NULL,
INDEX `idx_type`(`type` ASC) USING BTREE,
UNIQUE INDEX `uk_name`(`name` ASC,`type` ASC,`delete_at` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 93 ROW_FORMAT = Dynamic COMMENT = "计量单位表";
-- user_goals DDL
CREATE TABLE `user_goals` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT Comment "主键",
`user_id` INT UNSIGNED NOT NULL Comment "用户ID",
`daily_calories` INT NOT NULL DEFAULT 2000 Comment "每日热量目标 (kcal)",
`protein` INT NOT NULL DEFAULT 150 Comment "蛋白质 (g)",
`fat` INT NOT NULL DEFAULT 55 Comment "脂肪 (g)",
`carbohydrate` INT NOT NULL DEFAULT 225 Comment "碳水化合物 (g)",
`weight` DECIMAL(10,2) NOT NULL DEFAULT 60.00 Comment "体重目标 (kg)",
`created_at` DATETIME NULL Comment "创建时间",
`updated_at` DATETIME NULL Comment "更新时间",
UNIQUE INDEX `idx_user_id`(`user_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 5 ROW_FORMAT = Dynamic COMMENT = "用户目标设置";
-- user_steps DDL
CREATE TABLE `user_steps` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`user_id` INT NOT NULL Comment "用户ID",
`steps` INT NOT NULL DEFAULT 0 Comment "步数",
`record_date` DATE NOT NULL Comment "记录日期",
`created_at` DATETIME NULL,
`updated_at` DATETIME NULL,
UNIQUE INDEX `user_date`(`user_id` ASC,`record_date` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 322 ROW_FORMAT = Dynamic COMMENT = "用户步数记录表";
-- user_usages DDL
CREATE TABLE `user_usages` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "id",
`user_id` INT NULL,
`usage` INT NULL Comment "剩余次数",
`token` INT NULL,
`date` DATE NULL,
`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
UNIQUE INDEX `date`(`date` ASC,`user_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 27 ROW_FORMAT = Dynamic;
-- wa_admin_roles DDL
CREATE TABLE `wa_admin_roles` (`id` INT NOT NULL AUTO_INCREMENT Comment "主键",
`role_id` INT NOT NULL Comment "角色id",
`admin_id` INT NOT NULL Comment "管理员id",
UNIQUE INDEX `role_admin_id`(`role_id` ASC,`admin_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 2 ROW_FORMAT = Dynamic COMMENT = "管理员角色表";
-- wa_admins DDL
CREATE TABLE `wa_admins` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT Comment "ID",
`username` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "用户名",
`nickname` VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "昵称",
`password` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "密码",
`avatar` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '/app/admin/avatar.png' Comment "头像",
`email` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "邮箱",
`mobile` VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "手机",
`created_at` DATETIME NULL Comment "创建时间",
`updated_at` DATETIME NULL Comment "更新时间",
`login_at` DATETIME NULL Comment "登录时间",
`status` TINYINT NULL Comment "禁用",
UNIQUE INDEX `username`(`username` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 2 ROW_FORMAT = Dynamic COMMENT = "管理员表";
-- wa_options DDL
CREATE TABLE `wa_options` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "键",
`value` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "值",
`created_at` DATETIME NOT NULL DEFAULT '2022-08-15 00:00:00' Comment "创建时间",
`updated_at` DATETIME NOT NULL DEFAULT '2022-08-15 00:00:00' Comment "更新时间",
UNIQUE INDEX `name`(`name` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 23 ROW_FORMAT = Dynamic COMMENT = "选项表";
-- wa_roles DDL
CREATE TABLE `wa_roles` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT Comment "主键",
`name` VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "角色组",
`rules` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "权限",
`created_at` DATETIME NOT NULL Comment "创建时间",
`updated_at` DATETIME NOT NULL Comment "更新时间",
`pid` INT UNSIGNED NULL Comment "父级",
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 2 ROW_FORMAT = Dynamic COMMENT = "管理员角色";
-- wa_rules DDL
CREATE TABLE `wa_rules` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT Comment "主键",
`title` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "标题",
`icon` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "图标",
`key` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "标识",
`pid` INT UNSIGNED NULL DEFAULT 0 Comment "上级菜单",
`created_at` DATETIME NOT NULL Comment "创建时间",
`updated_at` DATETIME NOT NULL Comment "更新时间",
`href` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "url",
`type` INT NOT NULL DEFAULT 1 Comment "类型",
`weight` INT NULL DEFAULT 0 Comment "排序",
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 151 ROW_FORMAT = Dynamic COMMENT = "权限规则";
-- wa_uploads DDL
CREATE TABLE `wa_uploads` (`id` INT NOT NULL AUTO_INCREMENT Comment "主键",
`name` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "名称",
`url` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "文件",
`admin_id` INT NULL Comment "管理员",
`file_size` INT NOT NULL Comment "文件大小",
`mime_type` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "mime类型",
`image_width` INT NULL Comment "图片宽度",
`image_height` INT NULL Comment "图片高度",
`ext` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "扩展名",
`storage` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'local' Comment "存储位置",
`created_at` DATE NULL Comment "上传时间",
`category` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "类别",
`updated_at` DATE NULL Comment "更新时间",
INDEX `admin_id`(`admin_id` ASC) USING BTREE,
INDEX `category`(`category` ASC) USING BTREE,
INDEX `ext`(`ext` ASC) USING BTREE,
INDEX `name`(`name` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "附件";
-- wa_users DDL
CREATE TABLE `wa_users` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT Comment "主键",
`username` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "用户名",
`nickname` VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "昵称",
`password` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "密码",
`sex` ENUM("1","2","3") CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' Comment "性别1男2女3保密",
`avatar` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "头像",
`email` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "邮箱",
`mobile` VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "手机",
`openid` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "微信openid",
`unionid` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "微信unionid",
`signature` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "个性签名",
`background` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "背景图",
`age` INT NULL DEFAULT 0 Comment "年龄",
`tall` INT NULL DEFAULT 170 Comment "身高 cm",
`weight` DECIMAL(10,2) NULL DEFAULT 62.00 Comment "体重 kg",
`bmi` DECIMAL(10,2) NULL Comment "bmi",
`bust` DECIMAL(10,2) NULL Comment "胸围 cm",
`waist` DECIMAL(10,2) NULL Comment "腰围 cm",
`hip` DECIMAL(10,2) NULL Comment "臀围 cm",
`target` INT NULL Comment "卡路里目标",
`level` TINYINT NOT NULL DEFAULT 0 Comment "等级",
`birthday` DATE NULL Comment "生日",
`money` DECIMAL(10,2) NOT NULL DEFAULT 0.00 Comment "余额(元)",
`score` INT NOT NULL DEFAULT 0 Comment "积分",
`last_time` DATETIME NULL Comment "登录时间",
`last_ip` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "登录ip",
`join_time` DATETIME NULL Comment "注册时间",
`join_ip` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "注册ip",
`token` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "token",
`created_at` DATETIME NULL Comment "创建时间",
`updated_at` DATETIME NULL Comment "更新时间",
`role` INT NOT NULL DEFAULT 1 Comment "角色",
`status` TINYINT NOT NULL DEFAULT 1 Comment "禁用",
INDEX `email`(`email` ASC) USING BTREE,
INDEX `join_time`(`join_time` ASC) USING BTREE,
INDEX `mobile`(`mobile` ASC) USING BTREE,
UNIQUE INDEX `username`(`username` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 18 ROW_FORMAT = Dynamic COMMENT = "用户表";
SET FOREIGN_KEY_CHECKS = 1;
