<?php

namespace app\service\wechat;

use app\service\BaseGuzzleHttpClient;
use GuzzleHttp\Client;

abstract class BaseWechatClient extends BaseGuzzleHttpClient
{
    protected $appId;
    protected $appSecret;

    protected function __construct()
    {
        $this->client = new Client([
            'base_uri' => 'https://api.weixin.qq.com/',
            'timeout'  => 2.0,
            'headers'  => [
                'Content-Type' => 'application/json',
            ],
            'verify'   => false,
        ]);
        $this->loadAppid();
    }

    abstract protected function loadAppid();

    protected function handleResponse($response)
    {
        $data = parent::handleResponse($response); // TODO: Change the autogenerated stub

        if (isset($data['errcode']) && $data['errcode'] != 0) {
            throw new \Exception($data['errmsg'], $data['errcode']);
        }
        return $data;
    }
}
