<?php

namespace app\service\nutrition;

use app\service\BaseGuzzleHttpClient;

class Base extends BaseGuzzleHttpClient
{

    const API_KEY        = '5e59fa0a106cd9540a02c7acb8501205';
    const API_DOMAIN     = 'https://apis.tianapi.com/';
    const API_ERROR_CODE = [
        "100" => "内部服务器错误 报此错误码请及时反馈或等待官方修复",
        "110" => "当前API已下线 接口已下线无法使用，可关注相关通知",
        "120" => "API暂时维护中 接口暂时关闭维护中，请注意相关公告",
        "130" => "API调用频率超限 超过每秒请求数上限，可在控制台-接口管理中查询",
        "140" => "API没有调用权限 请检查是否自行在接口管理中停用或被禁用了该接口",
        "150" => "API可用次数不足 免费类接口套餐超限或计次类接口余额不足，点此查看说明",
        "160" => "账号未申请该API 请先在接口文档页面申请该接口，点此查看说明",
        "170" => "Referer请求来源受限 设置了Referer白名单，但来源Referer不在白名单内",
        "180" => "IP请求来源受限 设置了IP白名单，但来源IP不在白名单内",
        "190" => "当前key不可用 通常为账号无效，此状态无法恢复",
        "230" => "key错误或为空 请检查apikey是否填写错误，点此查看帮助",
        "240" => "缺少key参数 请检查是否传递了key参数或者编码格式是否符合要求",
        "250" => "数据返回为空 数据查询或转换失败，请检查输入值或注意中文编码问题",
        "260" => "参数值不得为空 请检查关键参数是否传递了空值",
        "270" => "参数值不符合要求 参数值不符合基本格式要求，点此查看说明",
        "280" => "缺少必要的参数 缺少必填的参数，请根据接口文档检查",
        "290" => "超过最大输入限制 参数值超过输入范围，请查看接口文档的说明"
    ];
    protected $client;

    protected function __construct()
    {
        $this->client = new \GuzzleHttp\Client([
            'base_uri' => self::API_DOMAIN,
            'verify'   => false,
        ]);
    }

    protected function handleResponse($response)
    {
        $data = parent::handleResponse($response); // TODO: Change the autogenerated stub
        if ((int)$data['code'] !== 200 && (int)$data['code'] != 250) {
            throw new \Exception(self::API_ERROR_CODE[(string)$data['code']]);
        }
        return $data['result']['list'] ?? [];
    }
}
